### ISSUE TITLE
请问可以发布上线吗

### ISSUE THREAD

**Issue by Bange666** [shichaohui/ColorUp#2]
作者大大您好，我看您的开源协议是Apache-2.0 license，并且分享了构建发布的步骤。
那请问我能在简单修改代码后,发布到微信小游戏线上嘛。

您在readme里又有"仅供学习交流，请勿商用"这一句，所以想向您确认一下，这里的"商用"只是指不要卖源码吗。

**Comment by shichaohui** [comment]
感谢您的关注，但是很抱歉，不可以发布的。
分享构建步骤是希望把完整的开发过程分享给大家，让大家可以顺利把项目跑起来，并在开发自己小游戏的过程中少走弯路。
祝您早日开发出爆款小游戏。
